# Generated by Django 3.1.3 on 2021-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210113_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
