# Generated by Django 3.1.3 on 2021-02-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210212_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
